#The CICD workflow file
name: ci

on:
  push:
    branches:
      - python-docker

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login into docker
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest




