name: ci

on:
  push:
    branches:
      - python-docker

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login into docker
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

